Update ping_every_9.yml now this will request to about page
this will search about

diff --git a/.github/workflows/ping_every_9.yml b/.github/workflows/ping_every_9.yml
--- a/.github/workflows/ping_every_9.yml
+++ b/.github/workflows/ping_every_9.yml
@@ -10,4 +10,4 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Curl ping to keep site awake
-        run: echo "Pinging at $(date)" && curl -s --max-time 120 https://www.kirananalyst.com/ || echo "Ping failed"
+        run: echo "Pinging at $(date)" && curl -s --max-time 120 https://www.kirananalyst.com/about || echo "Ping failed"
